components:
  schemas:
    Consignment:
      properties:
        AssociatedInvoice:
          items: {type: string}
          type: array
        AssociatedInvoiceDiscount:
          items: {type: string}
          type: array
        AssociatedInvoiceDiscountPercent:
          items: {type: string}
          type: array
        AvailabilityDue:
          items: {type: string}
          type: array
        COD: {type: string}
        CarrierAcceptance:
          items: {type: string}
          type: array
        CarrierAssigned: {type: string}
        ChargeableTransportationStage: {type: string}
        ChargeableWeight:
          items: {type: string}
          type: array
        ConsigneeAssigned: {type: string}
        ConsignmentItem: {type: string}
        ConsignorAssigned: {type: string}
        Containerization: {type: string}
        DeclaredValueForCarriage: {type: string}
        DeclaredValueForCustoms: {type: string}
        ExportExit:
          items: {type: string}
          type: array
        FOB: {type: string}
        FreightForwarderAssigned: {type: string}
        GoodsReleaseRestriction:
          items: {type: string}
          type: array
        GrossVolume:
          items: {type: string}
          type: array
        GrossWeight:
          items: {type: string}
          type: array
        Identification:
          items: {type: string}
          type: array
        IncludedConsignment:
          items: {$ref: '#/components/schemas/Consignment'}
          type: array
        IncludedConsignmentItems:
          properties:
            ChargeableWeight:
              items: {type: string}
              type: array
            DamageRemarks:
              items: {type: string}
              type: array
            DeclaredValueForCarriage: {type: string}
            DeclaredValueForCustoms: {type: string}
            DeclaredValueForStatistics: {type: string}
            DeliveryInstructions:
              items: {type: string}
              type: array
            FOB: {type: string}
            GrossVolume:
              items: {type: string}
              type: array
            GrossWeight:
              items: {type: string}
              type: array
            Identification:
              items: {type: string}
              type: array
            Information:
              items: {type: string}
              type: array
            InsuranceValue: {type: string}
            Invoice:
              items: {type: string}
              type: array
            LoadingLength: {type: string}
            NetWeight:
              items: {type: string}
              type: array
            Package:
              items: {type: string}
              type: array
            PackageType:
              items: {type: string}
              type: array
            Product:
              items: {type: string}
              type: array
            ProductDateType:
              items: {type: string}
              type: array
            Sequence: {type: string}
            SpecialInstructions:
              items: {type: string}
              type: array
            Tariff:
              items: {type: string}
              type: array
            TariffQuantity:
              items: {type: string}
              type: array
            TotalCharge: {type: string}
            TotalExportExitToImportEntryCharge: {type: string}
            TradeLineItem: {type: string}
            Type:
              items: {type: string}
              type: array
            TypeExtension:
              items: {type: string}
              type: array
        Information:
          items: {type: string}
          type: array
        InsurancePremium:
          items: {type: string}
          type: array
        InsuranceValue:
          items: {type: string}
          type: array
        LoadingLength:
          items: {type: string}
          type: array
        LoadingList: {type: string}
        LoadingSequence:
          items: {type: string}
          type: array
        NetVolume:
          items: {type: string}
          type: array
        NetWeight:
          items: {type: string}
          type: array
        NilCarriageValue: {type: string}
        NilCustomsValue: {type: string}
        NilInsuranceValue: {type: string}
        Package: {type: string}
        PackageType:
          items: {type: string}
          type: array
        PaymentArrangement: {type: string}
        PlannedTransportMovement:
          items: {$ref: '#/components/schemas/TransportMovement'}
          type: array
        RiskFactor:
          items: {type: string}
          type: array
        Sequence:
          items: {type: string}
          type: array
        ShipStores: {type: string}
        SummaryDescription:
          items: {type: string}
          type: array
        TotalAllowanceCharge:
          items: {type: string}
          type: array
        TotalCharge:
          items: {type: string}
          type: array
        TotalCollectCharge:
          items: {type: string}
          type: array
        TotalDisbursement:
          items: {type: string}
          type: array
        TotalExportExitToImportEntryCharge:
          items: {type: string}
          type: array
        TotalPrepaidCharge:
          items: {type: string}
          type: array
        TotalTareWeight:
          items: {type: string}
          type: array
        TradedParcel:
          items: {type: string}
          type: array
        TransportEquipment:
          items: {type: string}
          type: array
        TransportEquipmentSplitGoods: {type: string}
        TransportSplit: {type: string}
        TransportSplitDescription:
          items: {type: string}
          type: array
        TransshipmentPermission: {type: string}
        UnloadingSequence:
          items: {type: string}
          type: array
        WarehouseArrival: {type: string}
    ConsignmentItem:
      properties:
        ChargeableWeight:
          items: {type: string}
          type: array
        DamageRemarks:
          items: {type: string}
          type: array
        DeclaredValueForCarriage: {type: string}
        DeclaredValueForCustoms: {type: string}
        DeclaredValueForStatistics: {type: string}
        DeliveryInstructions:
          items: {type: string}
          type: array
        FOB: {type: string}
        GrossVolume:
          items: {type: string}
          type: array
        GrossWeight:
          items: {type: string}
          type: array
        Identification:
          items: {type: string}
          type: array
        Information:
          items: {type: string}
          type: array
        InsuranceValue: {type: string}
        Invoice:
          items: {type: string}
          type: array
        LoadingLength: {type: string}
        NetWeight:
          items: {type: string}
          type: array
        Package:
          items: {type: string}
          type: array
        PackageType:
          items: {type: string}
          type: array
        Product:
          items: {type: string}
          type: array
        ProductDateType:
          items: {type: string}
          type: array
        Sequence: {type: string}
        SpecialInstructions:
          items: {type: string}
          type: array
        Tariff:
          items: {type: string}
          type: array
        TariffQuantity:
          items: {type: string}
          type: array
        TotalCharge: {type: string}
        TotalExportExitToImportEntryCharge: {type: string}
        TradeLineItem: {type: string}
        Type:
          items: {type: string}
          type: array
        TypeExtension:
          items: {type: string}
          type: array
    Flight:
      allOf:
      - {$ref: '#/components/schemas/TransportMovement'}
      properties:
        Closing:
          items: {type: string}
          type: array
    TransportMeans:
      properties:
        CargoGrossWeight: {type: string}
        Commissioning:
          items: {type: string}
          type: array
        Conference: {type: string}
        DeadWeight: {type: string}
        Draught:
          items: {type: string}
          type: array
        DraughtLevel:
          items: {type: string}
          type: array
        DriverAccompanied:
          items: {type: string}
          type: array
        GrossWeight:
          items: {type: string}
          type: array
        Helipad: {type: string}
        HullMaterial:
          items: {type: string}
          type: array
        ISPSSecurityLevel:
          items: {type: string}
          type: array
        Identification:
          items: {type: string}
          type: array
        Length: {type: string}
        LoadedCargo:
          items: {type: string}
          type: array
        Name:
          items: {type: string}
          type: array
        NetWeight:
          items: {type: string}
          type: array
        OperationalStatus:
          items: {type: string}
          type: array
        RequiredLaneLength: {type: string}
        Role:
          items: {type: string}
          type: array
        Sequence:
          items: {type: string}
          type: array
        Speed:
          items: {type: string}
          type: array
        Type:
          items: {type: string}
          type: array
        TypeText:
          items: {type: string}
          type: array
        WasteReportingExemption: {type: string}
    TransportMovement:
      properties:
        BorderCrossing:
          items: {type: string}
          type: array
        CallPurpose:
          items: {type: string}
          type: array
        CargoDescription:
          items: {type: string}
          type: array
        Consignment:
          items: {type: string}
          type: array
        Crew: {type: string}
        Cycle:
          items: {type: string}
          type: array
        DangerousGoods: {type: string}
        Identification:
          items: {type: string}
          type: array
        Information:
          items: {type: string}
          type: array
        ManifestOnboard: {type: string}
        Mode:
          items: {type: string}
          type: array
        ModeText:
          items: {type: string}
          type: array
        Notification:
          items: {type: string}
          type: array
        OperationalCategory: {type: string}
        Package:
          items: {type: string}
          type: array
        Passenger: {type: string}
        PilotageExemption:
          items: {type: string}
          type: array
        Reason:
          items: {type: string}
          type: array
        RelatedTransportMovement:
          items: {$ref: '#/components/schemas/TransportMovement'}
          type: array
        Sequence:
          items: {type: string}
          type: array
        Service:
          items: {type: string}
          type: array
        ServiceText:
          items: {type: string}
          type: array
        Stage: {type: string}
        Start:
          items: {type: string}
          type: array
        Status:
          items: {type: string}
          type: array
        Stay:
          items: {type: string}
          type: array
        Total:
          items: {type: string}
          type: array
        TradedParcel: {type: string}
        TransitDirection:
          items: {type: string}
          type: array
        TransportEquipment: {type: string}
        Type:
          items: {type: string}
          type: array
        TypeText:
          items: {type: string}
          type: array
        UsedTransportMeans: {$ref: '#/components/schemas/TransportMeans'}
    Voyage:
      allOf:
      - {$ref: '#/components/schemas/TransportMovement'}
      properties: {}
info: {description: CC-Transport API - 1.0, title: CC-Transport API, version: '1.0'}
openapi: 3.0.0
paths:
  /Consignments:
    get:
      parameters:
      - description: ''
        in: query
        name: status
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {$ref: '#/components/schemas/Consignment'}
                type: array
          description: ''
    post:
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/Consignment'}
        description: ''
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Consignment'}
          description: ''
  /Consignments/{id}:
    delete:
      parameters:
      - description: ''
        in: path
        name: id
        required: true
        schema: {type: string}
      responses:
        '204': {description: Consignment deleted}
    get:
      parameters:
      - description: ''
        in: path
        name: id
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Consignment'}
          description: ''
    put:
      parameters:
      - description: ''
        in: path
        name: id
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/Consignment'}
        description: ''
        required: true
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Consignment'}
          description: ''
  /Voyages:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                items: {$ref: '#/components/schemas/Voyage'}
                type: array
          description: ''
  /Voyages/{id}:
    get:
      parameters:
      - description: ''
        in: path
        name: id
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Voyage'}
          description: ''
servers: []
